### ISSUE TITLE
I can't get my money back.

### ISSUE THREAD

**Issue by Gago55** [armanzakinyan/CoffeeMachine#1]
![Screenshot_1](https://user-images.githubusercontent.com/39292164/57333021-fd14a880-712c-11e9-9d9d-aae3e43d612b.png)
Man I take my coffee. Machine said that I have some change but I can't take my money back , I can only take another coffee with that money...Please help me to take my money back. 
Best Regards...

**Comment by armanzakinyan** [comment]
It was a good joke bro 👍🏿😂
